// GENERATED by scripts/photos.mjs — do not edit.
//
// Everything here is derived from the originals in photos/hobbies/. Words (alt, caption,
// location) and any hobby correction belong in PHOTO_TEXT in ./hobbies.ts, which the
// generator never writes to. Regenerate with: bun run photos
//
// Order follows filename order, and that is the order tiles fill the belts — rename to
// reorder.

/** One photo's mechanically-derived metadata. `hobby` is a filename guess. */
export interface GeneratedPhoto {
  id: string;
  src: string;
  full?: string;
  aspect: number;
  hobby: string;
  date?: string;
  gear?: string;
  accent: string;
}

export const GENERATED_PHOTOS: GeneratedPhoto[] = [
  {
    id: "img-0021",
    src: "assets/hobbies/img-0021.webp",
    full: "assets/hobbies/img-0021-full.webp",
    aspect: 0.75,
    hobby: "landscape",
    accent: "hsl(205 85% 62%)",
  },
  {
    id: "img-0034",
    src: "assets/hobbies/img-0034.webp",
    full: "assets/hobbies/img-0034-full.webp",
    aspect: 1.3333,
    hobby: "landscape",
    accent: "hsl(200 48% 70%)",
  },
  {
    id: "img-0048",
    src: "assets/hobbies/img-0048.webp",
    full: "assets/hobbies/img-0048-full.webp",
    aspect: 1.3333,
    hobby: "landscape",
    accent: "hsl(60 67% 54%)",
  },
  {
    id: "img-0060",
    src: "assets/hobbies/img-0060.webp",
    full: "assets/hobbies/img-0060-full.webp",
    aspect: 1.3333,
    hobby: "landscape",
    accent: "hsl(205 85% 62%)",
  },
  {
    id: "img-0095",
    src: "assets/hobbies/img-0095.webp",
    full: "assets/hobbies/img-0095-full.webp",
    aspect: 1.3333,
    hobby: "landscape",
    accent: "hsl(120 50% 54%)",
  },
  {
    id: "img-0105",
    src: "assets/hobbies/img-0105.webp",
    full: "assets/hobbies/img-0105-full.webp",
    aspect: 1.3333,
    hobby: "landscape",
    accent: "hsl(210 90% 70%)",
  },
  {
    id: "img-0108",
    src: "assets/hobbies/img-0108.webp",
    full: "assets/hobbies/img-0108-full.webp",
    aspect: 1.3333,
    hobby: "landscape",
    accent: "hsl(120 50% 54%)",
  },
];
