// GENERATED by scripts/photos.mjs assets — do not edit.
//
// Responsive derivatives of the committed originals in public/assets/. Regenerate with:
// bun run assets
//
// `src` values are bare and document-relative, like the hobbies manifest — run them
// through assetUrl() from ~/lib/assets before they reach the DOM, or they will 404 under
// the GitHub Pages base path. Build a srcSet the same way:
//
//   const srcSet = img.sources.map((s) => `${assetUrl(s.src)} ${s.width}w`).join(", ");
//
// The originals themselves are untouched and still the right file for anything that needs
// full resolution or a non-cropped frame (og:image, for instance).

/** One encoded size. `width`/`height` are the file's real pixel dimensions. */
export interface GeneratedImageSource {
  src: string;
  width: number;
  height: number;
}

export interface GeneratedImage {
  id: string;
  /** The committed original these were derived from, as a bare asset path. */
  original: string;
  /** True when the derivative is a centre-crop, not a plain downscale of the original. */
  cropped: boolean;
  /** Aspect ratio (width / height) of the derivatives, which may differ from the original. */
  aspect: number;
  /** Ascending by width; the last entry is the largest available. Never empty. */
  sources: GeneratedImageSource[];
}

export type GeneratedImageId =
  | "logo"
  | "portrait"
  | "verbalyst"
  | "healthut"
  | "patronpal"
  | "devducky"
  | "cornet-environment"
  | "cornet-predator"
  | "cornet-agent";

export const GENERATED_IMAGES: Record<GeneratedImageId, GeneratedImage> = {
  logo: {
    id: "logo",
    original: "assets/logo.png",
    cropped: false,
    aspect: 1,
    sources: [{ src: "assets/derived/logo-76w.webp", width: 76, height: 76 }],
  },
  portrait: {
    id: "portrait",
    original: "assets/portrait.jpeg",
    cropped: true,
    aspect: 0.8,
    sources: [
      { src: "assets/derived/portrait-424w.webp", width: 424, height: 530 },
      { src: "assets/derived/portrait-768w.webp", width: 768, height: 960 },
    ],
  },
  verbalyst: {
    id: "verbalyst",
    original: "assets/verbalyst.png",
    cropped: false,
    aspect: 2.1563,
    sources: [
      { src: "assets/derived/verbalyst-400w.webp", width: 400, height: 185 },
      { src: "assets/derived/verbalyst-800w.webp", width: 800, height: 371 },
    ],
  },
  healthut: {
    id: "healthut",
    original: "assets/Healthut.png",
    cropped: false,
    aspect: 1.7021,
    sources: [
      { src: "assets/derived/healthut-400w.webp", width: 400, height: 235 },
      { src: "assets/derived/healthut-800w.webp", width: 800, height: 470 },
    ],
  },
  patronpal: {
    id: "patronpal",
    original: "assets/patronPal.png",
    cropped: false,
    aspect: 1.7778,
    sources: [
      { src: "assets/derived/patronpal-400w.webp", width: 400, height: 225 },
      { src: "assets/derived/patronpal-800w.webp", width: 800, height: 450 },
    ],
  },
  devducky: {
    id: "devducky",
    original: "assets/devDucky.jpg",
    cropped: false,
    aspect: 1.5038,
    sources: [{ src: "assets/derived/devducky-400w.webp", width: 400, height: 266 }],
  },
  "cornet-environment": {
    id: "cornet-environment",
    original: "assets/cornet-environment.png",
    cropped: false,
    aspect: 1.5021,
    sources: [
      { src: "assets/derived/cornet-environment-400w.webp", width: 400, height: 266 },
      { src: "assets/derived/cornet-environment-721w.webp", width: 721, height: 480 },
    ],
  },
  "cornet-predator": {
    id: "cornet-predator",
    original: "assets/cornet-predator.png",
    cropped: false,
    aspect: 1.7556,
    sources: [
      { src: "assets/derived/cornet-predator-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/cornet-predator-790w.webp", width: 790, height: 450 },
    ],
  },
  "cornet-agent": {
    id: "cornet-agent",
    original: "assets/cornet-agent.png",
    cropped: false,
    aspect: 1.3937,
    sources: [
      { src: "assets/derived/cornet-agent-400w.webp", width: 400, height: 287 },
      { src: "assets/derived/cornet-agent-800w.webp", width: 800, height: 574 },
    ],
  },
};

/** 32x32 PNG cut from the logo. PNG because `<link rel="icon">` still wants one. */
export const FAVICON: GeneratedImageSource = {
  src: "assets/derived/favicon-32.png",
  width: 32,
  height: 32,
};
