// GENERATED by scripts/photos.mjs assets — do not edit.
//
// Responsive derivatives of the committed originals in public/assets/. Regenerate with:
// bun run assets
//
// `src` values are bare and document-relative, like the hobbies manifest — run them
// through assetUrl() from ~/lib/assets before they reach the DOM, or they will 404 under
// the GitHub Pages base path. Build a srcSet the same way:
//
//   const srcSet = img.sources.map((s) => `${assetUrl(s.src)} ${s.width}w`).join(", ");
//
// The originals themselves are untouched and still the right file for anything that needs
// full resolution or a non-cropped frame (og:image, for instance).

/** One encoded size. `width`/`height` are the file's real pixel dimensions. */
export interface GeneratedImageSource {
  src: string;
  width: number;
  height: number;
}

export interface GeneratedImage {
  id: string;
  /** The committed original these were derived from, as a bare asset path. */
  original: string;
  /** True when the derivative is a centre-crop, not a plain downscale of the original. */
  cropped: boolean;
  /** Aspect ratio (width / height) of the derivatives, which may differ from the original. */
  aspect: number;
  /** Ascending by width; the last entry is the largest available. Never empty. */
  sources: GeneratedImageSource[];
}

export type GeneratedImageId =
  | "logo"
  | "portrait"
  | "verbalyst"
  | "healthut"
  | "patronpal"
  | "devducky"
  | "sai-at-work"
  | "homepage"
  | "album"
  | "gallery"
  | "generated-walk"
  | "world-map"
  | "stats"
  | "architecture"
  | "capture"
  | "aerial-view-via-splat"
  | "rover"
  | "rover-top-view"
  | "vietnamese-dinner"
  | "winners"
  | "cornet-environment"
  | "cornet-predator"
  | "cornet-agent"
  | "landing"
  | "skill-tree"
  | "courses"
  | "skill-detail"
  | "quests"
  | "character"
  | "video-analysis"
  | "world"
  | "recorder"
  | "analysis"
  | "progress"
  | "tongue-twisters"
  | "resources"
  | "sparkers"
  | "notes"
  | "discord-bot"
  | "mic-rig"
  | "ide"
  | "observability"
  | "extension"
  | "creators"
  | "bench"
  | "flareups"
  | "whiteboard"
  | "wearable"
  | "readout"
  | "title-card"
  | "detection"
  | "hydropet"
  | "fair-play"
  | "civ6"
  | "genshin"
  | "railway-empire"
  | "mtg-arena"
  | "minecraft"
  | "clash-royale"
  | "frostpunk"
  | "cities-skylines-2"
  | "capital-one"
  | "cambridge"
  | "waterloo"
  | "marsh-mclennan"
  | "alt-protein-project"
  | "mathsoc"
  | "global-x"
  | "slimescholars";

export const GENERATED_IMAGES: Record<GeneratedImageId, GeneratedImage> = {
  logo: {
    id: "logo",
    original: "assets/logo.png",
    cropped: false,
    aspect: 1,
    sources: [{ src: "assets/derived/logo-76w.webp", width: 76, height: 76 }],
  },
  portrait: {
    id: "portrait",
    original: "assets/portrait.jpeg",
    cropped: true,
    aspect: 0.8,
    sources: [
      { src: "assets/derived/portrait-424w.webp", width: 424, height: 530 },
      { src: "assets/derived/portrait-768w.webp", width: 768, height: 960 },
    ],
  },
  verbalyst: {
    id: "verbalyst",
    original: "assets/verbalyst.png",
    cropped: false,
    aspect: 2.1563,
    sources: [
      { src: "assets/derived/verbalyst-400w.webp", width: 400, height: 185 },
      { src: "assets/derived/verbalyst-800w.webp", width: 800, height: 371 },
    ],
  },
  healthut: {
    id: "healthut",
    original: "assets/Healthut.png",
    cropped: false,
    aspect: 1.7021,
    sources: [
      { src: "assets/derived/healthut-400w.webp", width: 400, height: 235 },
      { src: "assets/derived/healthut-800w.webp", width: 800, height: 470 },
    ],
  },
  patronpal: {
    id: "patronpal",
    original: "assets/patronPal.png",
    cropped: false,
    aspect: 1.7778,
    sources: [
      { src: "assets/derived/patronpal-400w.webp", width: 400, height: 225 },
      { src: "assets/derived/patronpal-800w.webp", width: 800, height: 450 },
    ],
  },
  devducky: {
    id: "devducky",
    original: "assets/devDucky.jpg",
    cropped: false,
    aspect: 1.5038,
    sources: [{ src: "assets/derived/devducky-400w.webp", width: 400, height: 266 }],
  },
  "sai-at-work": {
    id: "sai-at-work",
    original: "assets/spark/sai-at-work.png",
    cropped: false,
    aspect: 1.7544,
    sources: [
      { src: "assets/derived/sai-at-work-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/sai-at-work-800w.webp", width: 800, height: 456 },
    ],
  },
  homepage: {
    id: "homepage",
    original: "assets/spark/homepage.png",
    cropped: false,
    aspect: 2.1978,
    sources: [
      { src: "assets/derived/homepage-400w.webp", width: 400, height: 182 },
      { src: "assets/derived/homepage-800w.webp", width: 800, height: 364 },
    ],
  },
  album: {
    id: "album",
    original: "assets/spark/album.png",
    cropped: false,
    aspect: 1.7544,
    sources: [
      { src: "assets/derived/album-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/album-800w.webp", width: 800, height: 456 },
    ],
  },
  gallery: {
    id: "gallery",
    original: "assets/spark/gallery.png",
    cropped: false,
    aspect: 1.7544,
    sources: [
      { src: "assets/derived/gallery-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/gallery-800w.webp", width: 800, height: 456 },
    ],
  },
  "generated-walk": {
    id: "generated-walk",
    original: "assets/spark/generated-walk.jpg",
    cropped: false,
    aspect: 1.7621,
    sources: [
      { src: "assets/derived/generated-walk-400w.webp", width: 400, height: 227 },
      { src: "assets/derived/generated-walk-800w.webp", width: 800, height: 454 },
    ],
  },
  "world-map": {
    id: "world-map",
    original: "assets/spark/world-map.png",
    cropped: false,
    aspect: 1.7621,
    sources: [
      { src: "assets/derived/world-map-400w.webp", width: 400, height: 227 },
      { src: "assets/derived/world-map-800w.webp", width: 800, height: 454 },
    ],
  },
  stats: {
    id: "stats",
    original: "assets/spark/stats.png",
    cropped: false,
    aspect: 1.7582,
    sources: [
      { src: "assets/derived/stats-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/stats-800w.webp", width: 800, height: 455 },
    ],
  },
  architecture: {
    id: "architecture",
    original: "assets/spark/architecture.png",
    cropped: false,
    aspect: 1.7582,
    sources: [
      { src: "assets/derived/architecture-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/architecture-800w.webp", width: 800, height: 455 },
    ],
  },
  capture: {
    id: "capture",
    original: "assets/spark/capture.png",
    cropped: false,
    aspect: 1.7544,
    sources: [
      { src: "assets/derived/capture-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/capture-800w.webp", width: 800, height: 456 },
    ],
  },
  "aerial-view-via-splat": {
    id: "aerial-view-via-splat",
    original: "assets/spark/aerial-view-via-splat.jpg",
    cropped: false,
    aspect: 1.7505,
    sources: [
      { src: "assets/derived/aerial-view-via-splat-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/aerial-view-via-splat-800w.webp", width: 800, height: 457 },
    ],
  },
  rover: {
    id: "rover",
    original: "assets/spark/rover.jpg",
    cropped: false,
    aspect: 1.3333,
    sources: [
      { src: "assets/derived/rover-400w.webp", width: 400, height: 300 },
      { src: "assets/derived/rover-800w.webp", width: 800, height: 600 },
    ],
  },
  "rover-top-view": {
    id: "rover-top-view",
    original: "assets/spark/rover-top-view.jpg",
    cropped: false,
    aspect: 0.7498,
    sources: [
      { src: "assets/derived/rover-top-view-400w.webp", width: 400, height: 534 },
      { src: "assets/derived/rover-top-view-800w.webp", width: 800, height: 1067 },
    ],
  },
  "vietnamese-dinner": {
    id: "vietnamese-dinner",
    original: "assets/spark/vietnamese-dinner.jpg",
    cropped: false,
    aspect: 1.7505,
    sources: [
      { src: "assets/derived/vietnamese-dinner-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/vietnamese-dinner-800w.webp", width: 800, height: 457 },
    ],
  },
  winners: {
    id: "winners",
    original: "assets/spark/winners.jpg",
    cropped: false,
    aspect: 1.3008,
    sources: [
      { src: "assets/derived/winners-400w.webp", width: 400, height: 308 },
      { src: "assets/derived/winners-800w.webp", width: 800, height: 615 },
    ],
  },
  "cornet-environment": {
    id: "cornet-environment",
    original: "assets/cornet-environment.png",
    cropped: false,
    aspect: 1.5021,
    sources: [
      { src: "assets/derived/cornet-environment-400w.webp", width: 400, height: 266 },
      { src: "assets/derived/cornet-environment-721w.webp", width: 721, height: 480 },
    ],
  },
  "cornet-predator": {
    id: "cornet-predator",
    original: "assets/cornet-predator.png",
    cropped: false,
    aspect: 1.7556,
    sources: [
      { src: "assets/derived/cornet-predator-400w.webp", width: 400, height: 228 },
      { src: "assets/derived/cornet-predator-790w.webp", width: 790, height: 450 },
    ],
  },
  "cornet-agent": {
    id: "cornet-agent",
    original: "assets/cornet-agent.png",
    cropped: false,
    aspect: 1.3937,
    sources: [
      { src: "assets/derived/cornet-agent-400w.webp", width: 400, height: 287 },
      { src: "assets/derived/cornet-agent-800w.webp", width: 800, height: 574 },
    ],
  },
  landing: {
    id: "landing",
    original: "assets/scaleup/landing.jpg",
    cropped: false,
    aspect: 2.0305,
    sources: [
      { src: "assets/derived/landing-400w.webp", width: 400, height: 197 },
      { src: "assets/derived/landing-800w.webp", width: 800, height: 394 },
    ],
  },
  "skill-tree": {
    id: "skill-tree",
    original: "assets/scaleup/skill-tree.jpg",
    cropped: false,
    aspect: 2.0305,
    sources: [
      { src: "assets/derived/skill-tree-400w.webp", width: 400, height: 197 },
      { src: "assets/derived/skill-tree-800w.webp", width: 800, height: 394 },
    ],
  },
  courses: {
    id: "courses",
    original: "assets/scaleup/courses.jpg",
    cropped: false,
    aspect: 2.0305,
    sources: [
      { src: "assets/derived/courses-400w.webp", width: 400, height: 197 },
      { src: "assets/derived/courses-800w.webp", width: 800, height: 394 },
    ],
  },
  "skill-detail": {
    id: "skill-detail",
    original: "assets/scaleup/skill-detail.jpg",
    cropped: false,
    aspect: 2.0305,
    sources: [
      { src: "assets/derived/skill-detail-400w.webp", width: 400, height: 197 },
      { src: "assets/derived/skill-detail-800w.webp", width: 800, height: 394 },
    ],
  },
  quests: {
    id: "quests",
    original: "assets/scaleup/quests.jpg",
    cropped: false,
    aspect: 2.0305,
    sources: [
      { src: "assets/derived/quests-400w.webp", width: 400, height: 197 },
      { src: "assets/derived/quests-800w.webp", width: 800, height: 394 },
    ],
  },
  character: {
    id: "character",
    original: "assets/scaleup/character.jpg",
    cropped: false,
    aspect: 2.0305,
    sources: [
      { src: "assets/derived/character-400w.webp", width: 400, height: 197 },
      { src: "assets/derived/character-800w.webp", width: 800, height: 394 },
    ],
  },
  "video-analysis": {
    id: "video-analysis",
    original: "assets/scaleup/video-analysis.jpg",
    cropped: false,
    aspect: 2.0305,
    sources: [
      { src: "assets/derived/video-analysis-400w.webp", width: 400, height: 197 },
      { src: "assets/derived/video-analysis-800w.webp", width: 800, height: 394 },
    ],
  },
  world: {
    id: "world",
    original: "assets/scaleup/world.jpg",
    cropped: false,
    aspect: 2.0305,
    sources: [
      { src: "assets/derived/world-400w.webp", width: 400, height: 197 },
      { src: "assets/derived/world-800w.webp", width: 800, height: 394 },
    ],
  },
  recorder: {
    id: "recorder",
    original: "assets/verbalyst/recorder.png",
    cropped: false,
    aspect: 2.139,
    sources: [
      { src: "assets/derived/recorder-400w.webp", width: 400, height: 187 },
      { src: "assets/derived/recorder-800w.webp", width: 800, height: 374 },
    ],
  },
  analysis: {
    id: "analysis",
    original: "assets/verbalyst/analysis.png",
    cropped: false,
    aspect: 2.1505,
    sources: [
      { src: "assets/derived/analysis-400w.webp", width: 400, height: 186 },
      { src: "assets/derived/analysis-800w.webp", width: 800, height: 372 },
    ],
  },
  progress: {
    id: "progress",
    original: "assets/verbalyst/progress.png",
    cropped: false,
    aspect: 3.2129,
    sources: [
      { src: "assets/derived/progress-400w.webp", width: 400, height: 125 },
      { src: "assets/derived/progress-800w.webp", width: 800, height: 249 },
    ],
  },
  "tongue-twisters": {
    id: "tongue-twisters",
    original: "assets/verbalyst/tongue-twisters.png",
    cropped: false,
    aspect: 2.3055,
    sources: [
      { src: "assets/derived/tongue-twisters-400w.webp", width: 400, height: 174 },
      { src: "assets/derived/tongue-twisters-800w.webp", width: 800, height: 347 },
    ],
  },
  resources: {
    id: "resources",
    original: "assets/healthut/resources.png",
    cropped: false,
    aspect: 1.7021,
    sources: [
      { src: "assets/derived/resources-400w.webp", width: 400, height: 235 },
      { src: "assets/derived/resources-800w.webp", width: 800, height: 470 },
    ],
  },
  sparkers: {
    id: "sparkers",
    original: "assets/healthut/sparkers.png",
    cropped: false,
    aspect: 1.6985,
    sources: [
      { src: "assets/derived/sparkers-400w.webp", width: 400, height: 235 },
      { src: "assets/derived/sparkers-800w.webp", width: 800, height: 471 },
    ],
  },
  notes: {
    id: "notes",
    original: "assets/healthut/notes.png",
    cropped: false,
    aspect: 1.6878,
    sources: [
      { src: "assets/derived/notes-400w.webp", width: 400, height: 237 },
      { src: "assets/derived/notes-800w.webp", width: 800, height: 474 },
    ],
  },
  "discord-bot": {
    id: "discord-bot",
    original: "assets/healthut/discord-bot.png",
    cropped: false,
    aspect: 1.6807,
    sources: [
      { src: "assets/derived/discord-bot-400w.webp", width: 400, height: 238 },
      { src: "assets/derived/discord-bot-800w.webp", width: 800, height: 476 },
    ],
  },
  "mic-rig": {
    id: "mic-rig",
    original: "assets/devducky/mic-rig.jpg",
    cropped: false,
    aspect: 0.7498,
    sources: [
      { src: "assets/derived/mic-rig-400w.webp", width: 400, height: 533 },
      { src: "assets/derived/mic-rig-800w.webp", width: 800, height: 1067 },
    ],
  },
  ide: {
    id: "ide",
    original: "assets/devducky/ide.png",
    cropped: false,
    aspect: 1.9048,
    sources: [
      { src: "assets/derived/ide-400w.webp", width: 400, height: 210 },
      { src: "assets/derived/ide-800w.webp", width: 800, height: 420 },
    ],
  },
  observability: {
    id: "observability",
    original: "assets/devducky/observability.png",
    cropped: false,
    aspect: 1.9324,
    sources: [
      { src: "assets/derived/observability-400w.webp", width: 400, height: 207 },
      { src: "assets/derived/observability-800w.webp", width: 800, height: 414 },
    ],
  },
  extension: {
    id: "extension",
    original: "assets/patronpal/extension.png",
    cropped: false,
    aspect: 1.8913,
    sources: [
      { src: "assets/derived/extension-400w.webp", width: 400, height: 211 },
      { src: "assets/derived/extension-800w.webp", width: 800, height: 423 },
    ],
  },
  creators: {
    id: "creators",
    original: "assets/patronpal/creators.png",
    cropped: false,
    aspect: 1.7738,
    sources: [
      { src: "assets/derived/creators-400w.webp", width: 400, height: 225 },
      { src: "assets/derived/creators-800w.webp", width: 800, height: 451 },
    ],
  },
  bench: {
    id: "bench",
    original: "assets/smartskin/bench.jpg",
    cropped: false,
    aspect: 1.3333,
    sources: [
      { src: "assets/derived/bench-400w.webp", width: 400, height: 300 },
      { src: "assets/derived/bench-800w.webp", width: 800, height: 600 },
    ],
  },
  flareups: {
    id: "flareups",
    original: "assets/smartskin/flareups.png",
    cropped: false,
    aspect: 2.0833,
    sources: [
      { src: "assets/derived/flareups-400w.webp", width: 400, height: 192 },
      { src: "assets/derived/flareups-800w.webp", width: 800, height: 384 },
    ],
  },
  whiteboard: {
    id: "whiteboard",
    original: "assets/smartskin/whiteboard.jpg",
    cropped: false,
    aspect: 1.3333,
    sources: [
      { src: "assets/derived/whiteboard-400w.webp", width: 400, height: 300 },
      { src: "assets/derived/whiteboard-800w.webp", width: 800, height: 600 },
    ],
  },
  wearable: {
    id: "wearable",
    original: "assets/smartskin/wearable.jpg",
    cropped: false,
    aspect: 1.3333,
    sources: [
      { src: "assets/derived/wearable-400w.webp", width: 400, height: 300 },
      { src: "assets/derived/wearable-800w.webp", width: 800, height: 600 },
    ],
  },
  readout: {
    id: "readout",
    original: "assets/smartskin/readout.png",
    cropped: false,
    aspect: 4.908,
    sources: [
      { src: "assets/derived/readout-400w.webp", width: 400, height: 82 },
      { src: "assets/derived/readout-800w.webp", width: 800, height: 163 },
    ],
  },
  "title-card": {
    id: "title-card",
    original: "assets/hydrohomies/title-card.png",
    cropped: false,
    aspect: 1.7897,
    sources: [
      { src: "assets/derived/title-card-400w.webp", width: 400, height: 224 },
      { src: "assets/derived/title-card-800w.webp", width: 800, height: 447 },
    ],
  },
  detection: {
    id: "detection",
    original: "assets/hydrohomies/detection.png",
    cropped: false,
    aspect: 1.0914,
    sources: [
      { src: "assets/derived/detection-400w.webp", width: 400, height: 366 },
      { src: "assets/derived/detection-764w.webp", width: 764, height: 700 },
    ],
  },
  hydropet: {
    id: "hydropet",
    original: "assets/hydrohomies/hydropet.png",
    cropped: false,
    aspect: 1.7738,
    sources: [
      { src: "assets/derived/hydropet-400w.webp", width: 400, height: 226 },
      { src: "assets/derived/hydropet-800w.webp", width: 800, height: 451 },
    ],
  },
  "fair-play": {
    id: "fair-play",
    original: "assets/hydrohomies/fair-play.png",
    cropped: false,
    aspect: 1.7817,
    sources: [
      { src: "assets/derived/fair-play-400w.webp", width: 400, height: 224 },
      { src: "assets/derived/fair-play-800w.webp", width: 800, height: 449 },
    ],
  },
  civ6: {
    id: "civ6",
    original: "assets/games/civ6.jpg",
    cropped: false,
    aspect: 0.6667,
    sources: [
      { src: "assets/derived/civ6-200w.webp", width: 200, height: 300 },
      { src: "assets/derived/civ6-400w.webp", width: 400, height: 600 },
    ],
  },
  genshin: {
    id: "genshin",
    original: "assets/games/genshin.jpg",
    cropped: false,
    aspect: 1,
    sources: [
      { src: "assets/derived/genshin-200w.webp", width: 200, height: 200 },
      { src: "assets/derived/genshin-400w.webp", width: 400, height: 400 },
    ],
  },
  "railway-empire": {
    id: "railway-empire",
    original: "assets/games/railway-empire.jpg",
    cropped: false,
    aspect: 0.6667,
    sources: [
      { src: "assets/derived/railway-empire-200w.webp", width: 200, height: 300 },
      { src: "assets/derived/railway-empire-400w.webp", width: 400, height: 600 },
    ],
  },
  "mtg-arena": {
    id: "mtg-arena",
    original: "assets/games/mtg-arena.jpg",
    cropped: false,
    aspect: 0.6667,
    sources: [
      { src: "assets/derived/mtg-arena-200w.webp", width: 200, height: 300 },
      { src: "assets/derived/mtg-arena-400w.webp", width: 400, height: 600 },
    ],
  },
  minecraft: {
    id: "minecraft",
    original: "assets/games/minecraft.jpg",
    cropped: false,
    aspect: 1,
    sources: [
      { src: "assets/derived/minecraft-200w.webp", width: 200, height: 200 },
      { src: "assets/derived/minecraft-400w.webp", width: 400, height: 400 },
    ],
  },
  "clash-royale": {
    id: "clash-royale",
    original: "assets/games/clash-royale.jpg",
    cropped: false,
    aspect: 1,
    sources: [
      { src: "assets/derived/clash-royale-200w.webp", width: 200, height: 200 },
      { src: "assets/derived/clash-royale-400w.webp", width: 400, height: 400 },
    ],
  },
  frostpunk: {
    id: "frostpunk",
    original: "assets/games/frostpunk.jpg",
    cropped: false,
    aspect: 0.6667,
    sources: [
      { src: "assets/derived/frostpunk-200w.webp", width: 200, height: 300 },
      { src: "assets/derived/frostpunk-400w.webp", width: 400, height: 600 },
    ],
  },
  "cities-skylines-2": {
    id: "cities-skylines-2",
    original: "assets/games/cities-skylines-2.jpg",
    cropped: false,
    aspect: 0.6667,
    sources: [
      { src: "assets/derived/cities-skylines-2-200w.webp", width: 200, height: 300 },
      { src: "assets/derived/cities-skylines-2-400w.webp", width: 400, height: 600 },
    ],
  },
  "capital-one": {
    id: "capital-one",
    original: "assets/logos/capital-one.png",
    cropped: false,
    aspect: 2.7778,
    sources: [
      { src: "assets/derived/capital-one-400w.webp", width: 400, height: 144 },
      { src: "assets/derived/capital-one-800w.webp", width: 800, height: 288 },
    ],
  },
  cambridge: {
    id: "cambridge",
    original: "assets/logos/cambridge.png",
    cropped: false,
    aspect: 4.9689,
    sources: [
      { src: "assets/derived/cambridge-400w.webp", width: 400, height: 81 },
      { src: "assets/derived/cambridge-800w.webp", width: 800, height: 161 },
    ],
  },
  waterloo: {
    id: "waterloo",
    original: "assets/logos/waterloo.png",
    cropped: false,
    aspect: 3.3484,
    sources: [
      { src: "assets/derived/waterloo-400w.webp", width: 400, height: 119 },
      { src: "assets/derived/waterloo-519w.webp", width: 519, height: 155 },
    ],
  },
  "marsh-mclennan": {
    id: "marsh-mclennan",
    original: "assets/logos/marsh-mclennan.png",
    cropped: false,
    aspect: 11.9403,
    sources: [
      { src: "assets/derived/marsh-mclennan-400w.webp", width: 400, height: 34 },
      { src: "assets/derived/marsh-mclennan-800w.webp", width: 800, height: 67 },
    ],
  },
  "alt-protein-project": {
    id: "alt-protein-project",
    original: "assets/logos/alt-protein-project.png",
    cropped: false,
    aspect: 3.9801,
    sources: [
      { src: "assets/derived/alt-protein-project-400w.webp", width: 400, height: 101 },
      { src: "assets/derived/alt-protein-project-800w.webp", width: 800, height: 201 },
    ],
  },
  mathsoc: {
    id: "mathsoc",
    original: "assets/logos/mathsoc.png",
    cropped: false,
    aspect: 1,
    sources: [{ src: "assets/derived/mathsoc-287w.webp", width: 287, height: 287 }],
  },
  "global-x": {
    id: "global-x",
    original: "assets/logos/global-x.png",
    cropped: false,
    aspect: 2.9545,
    sources: [
      { src: "assets/derived/global-x-400w.webp", width: 400, height: 135 },
      { src: "assets/derived/global-x-650w.webp", width: 650, height: 220 },
    ],
  },
  slimescholars: {
    id: "slimescholars",
    original: "assets/logos/slimescholars.png",
    cropped: false,
    aspect: 1,
    sources: [{ src: "assets/derived/slimescholars-180w.webp", width: 180, height: 180 }],
  },
};

/** 32x32 PNG cut from the logo. PNG because `<link rel="icon">` still wants one. */
export const FAVICON: GeneratedImageSource = {
  src: "assets/derived/favicon-32.png",
  width: 32,
  height: 32,
};
